[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
deviant = "F9r3DZXQ4tJD4MbQokKBcKzck9EzBXkeTWNUzyuvSyR4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/cit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
